name: DevCard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "17 0 * * *"
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.0.0
        with:
          user_id: ${{ secrets.USER_I }}
          commit_message: "chore: update ${filename}"
